### ISSUE TITLE
Add minimal permissions guidance

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoft/m365-developer-proxy#213]
Add guidance for Microsoft Graph that helps customers verify that their apps use minimal permissions.

**Comment by sebastienlevert** [comment]
Update on the topic. We are meeting with the DevX API team this week to get more details on the rollout and the underlying capabilities we could leverage to identify minimal permissions guidance as part of the Proxy!

**Comment by garrytrinder** [comment]
Implemented in v0.8

**Comment by waldekmastykarz** [comment]
@garrytrinder this is not quite the same as the minimal permissions plugin that we've got now. The idea here is, that we compare the scopes/roles from the access token with minimal permissions for the given set of endpoints and verify that the app isn't overconsented.
