### ISSUE TITLE
MinimalPermissionsGuidancePlugin - Suggestion: Could it ignore, or look into the payload of $batch?

### ISSUE THREAD

**Issue by jimmywim** [microsoft/m365-developer-proxy#283]
The MinPerms plugin can't read permissions information for $batch.

The requests are in the payload, so the plugin could look into the payload to check the requests.

Current output:

```
Couldn't determine minimal permissions for the following URLs:
- /$batch (Permissions information for 'POST /$batch' was not found.)
```

**Comment by waldekmastykarz** [comment]
Great suggestion! We should definitely add it!
