### ISSUE TITLE
Ignore $select suggestion for $value endpoint on /photo

### ISSUE THREAD

**Issue by jimmywim** [microsoft/m365-developer-proxy#286]
The output can be a bit polluted with suggestions to use `$select` where it's irrelevant, for example, the User Photo endpoint `$value` which returns binary data, `$select` is irrelevant here.

**Comment by waldekmastykarz** [comment]
Correct. We're looking for a more robust way to suggest the use of `$select` where it's truly applicable, rather than what we've got available now. As a workaround, we could disable it explicitly on `$value` endpoints. Any other use cases that we should consider for the temporary workaround?

**Comment by waldekmastykarz** [comment]
Related to #107

**Comment by jimmywim** [comment]
Thanks Waldek - no other endpoints immediately spring to mind, but I'll note it in here if I come across any!
