### ISSUE TITLE
Provide more accurate error message when using options from disabled plugins

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoft/m365-developer-proxy#289]
We should also consider how we can provide a better message in scenarios like this.

`--summary-file-path` is a known option, so we should be able to provide a more helpful message, like

> To use `<option name>` you need to enable `<name of plugin>` plugin.

_Originally posted by @garrytrinder in https://github.com/microsoft/m365-developer-proxy/issues/282#issuecomment-1621492626_

**Comment by waldekmastykarz** [comment]
The biggest consideration here is, that options are only known to plugins, and if a plugin is disabled, it's not loaded so we have no way of knowing which options it exposes, unless we leak responsibility and keep the list of known options, which goes against the modularity of plugins.

**Comment by garrytrinder** [comment]
> The biggest consideration here is, that options are only known to plugins, and if a plugin is disabled, it's not loaded so we have no way of knowing which options it exposes

I agree and whilst it would be great to match an option directly with a plugin, doing so would add additional complexity. That said, I think we could provide a hint or at least guide the user in the right direction.

In the case of #282, when the `ExecutionSummaryPlugin` is disabled, we throw an error and show the help output to list available options. To your point @waldekmastykarz, we don't list `--summary-file-path` and `--summary-group-by` as a valid options in the output as the plugin is not loaded.

Maybe we should consider adding a message after the errors, before the help information that asks `have you not loaded a plugin?` or something to that effect. We could also provide a short URL in the message to provide some extra guidance around enabling and disabling plugins which could be useful to new users.


```

**Comment by waldekmastykarz** [comment]
> Maybe we should consider adding a message after the errors, before the help information that asks `have you not loaded a plugin?` or something to that effect.
> 
> We could also provide a short URL in the message to provide some extra guidance around enabling and disabling plugins which could be useful to new users.

Great idea! Love it! Let's do that
