### ISSUE TITLE
Add support for mocking Graph batch responses

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoft/m365-developer-proxy#307]
Extend the proxy with support for mocking responses inside Graph batch requests.

Right now, we support mocking requests based on their URL and method. For Graph batch requests this is insufficient, because while the method and the URL are always the same, the body of the request actually describes which endpoints are being called.

We should create a new plugin capable of mocking Graph batch responses. It would use the existing mock infrastructure, and on top add the ability to detect batch requests, unpack their requests, mock responses, build a batch response and return it to the client.

Before we proceed with implementation, we need to decide how to handle requests for which we have no mocks. We could do it in a few ways:

1. Pass the batch request through to Graph, intercept the response and replace what we can with mocks
2. Mock the requests that we can. Manually execute requests to Graph that we can't mock and stitch everything together into a mock batch response
3. Mock the requests that we can and return a 404 response for requests that we can't mock

Approach no. 3 is the easiest to build. It's the most accurate but it gives the user sufficient information to see which mocks are missing.
Approaches 1 and 2 give the user a more accurate response but are significantly more complex and error prone to implement.

I suggest that we started with no. 3.

**Comment by waldekmastykarz** [comment]
@gavinbarron @sebastienlevert @garrytrinder any opinions or other ideas?

**Comment by sebastienlevert** [comment]
This is an interesting topic and I'd vote for 3. Mocks should be completely isolated and should not require "half" of the data to come from the outside world. My recommendation would be to go with 3 and be very explicit in the error we return as part of the responses that the mock was missing as part of the 404.

That brings another discussion... Should we have a mode where proxy ONLY mocks and never calls Graph? Right now AFAIK we are providing an hybrid where "if" there is a mock, we return the mock but if not, we return Graph data right? This behavior would be different from the one suggested, though...

**Comment by waldekmastykarz** [comment]
> Should we have a mode where proxy ONLY mocks and never calls Graph? Right now AFAIK we are providing an hybrid where "if" there is a mock, we return the mock but if not, we return Graph data right? This behavior would be different from the one suggested, though

This is a good question and seems like a good addition to our mock plugins, where you could flip the switch and disable passing through unmocked requests and instead return a `502 Bad Gateway` or a similar response. Great suggestion @sebastienlevert! 👍
