### ISSUE TITLE
[Wiki] Wrong link to responses.sample.json

### ISSUE THREAD

**Issue by heinrich-ulbricht** [microsoft/m365-developer-proxy#318]
On https://github.com/microsoft/m365-developer-proxy/wiki/Mock-responses there is a link to responses.sample.json that is dead.

The link still points to https://github.com/microsoft/m365-developer-proxy/blob/main/msgraph-developer-proxy/responses.sample.json but should point to https://github.com/microsoft/m365-developer-proxy/blob/main/m365-developer-proxy/responses.sample.json instead.

I'd also like to have a hint on this page that wildcards can be used safely in `responses.sample.json` (like `https://*.api.com/*`).

I'd love to create a pull request but after googling how to do pull requests for a GitHub _wiki_ (as opposed to "just" _code_) I don't dare to try that.

**Comment by garrytrinder** [comment]
Good catch, thanks for raising the issue @heinrich-ulbricht and sorry for the trouble.

I've fixed the broken link, seems we didn't quite capture all links referring to the old repo.

> I'd also like to have a hint on this page that wildcards can be used safely in responses.sample.json (like https://*.api.com/*).

Great idea, we should certainly include that.

> I'd love to create a pull request but after googling how to do pull requests for a GitHub wiki (as opposed to "just" code) I don't dare to try that.

Yes, unfortunately this is a limitation of the wiki that it does not support PRs. We do have plans to move our docs to a more appropriate place, so this will be possible in the future.

**Comment by garrytrinder** [comment]
I've made an update to https://github.com/microsoft/m365-developer-proxy/wiki/Mock-responses to include a section on the use of wildcards. 

Thanks for the suggestion @heinrich-ulbricht if you have any other suggestions or feedback, please do raise an issue. 

Thanks again. ❤️

**Comment by heinrich-ulbricht** [comment]
Perfect, thanks for the update!
