### ISSUE TITLE
[Feature idea/request] Delay all traffic

### ISSUE THREAD

**Issue by Tanddant** [microsoft/m365-developer-proxy#321]
I was developing a PowerShell script earlier, that was using NVM, turns out that the nodejs servers where incredibly slow, probably overloaded.

That made me realize it's next to impossible to demonstrate/test how your app does under terrible network conditions, it can be done in the browser using devtools, and throttling, but being able to "slow down" requests to emulate a slow connection would be awesome!

[Twitter discussion](https://twitter.com/tanddant/status/1692202230219145225)

**Comment by jimmywim** [comment]
This should offer the option to set the download data rate of incoming traffic, as well as "time to first bytes". And have both options vary chaotically.

**Comment by waldekmastykarz** [comment]
Awesome suggestions! Thank you!

**Comment by jimmywim** [comment]
> The response delay would be easy for us to implement. For the throughput rate, we’d need to think some more

You're gonna have to do some hardcore maths! And some tricky buffering or local device cache storage to stop runaway memory usage!

**Comment by jimmywim** [comment]
In fact, I like my idea of a local device cache.

When connection slowdown is enabled, storage the response on disk, then slowly feed it to the client, then delete the stored request.

**Comment by waldekmastykarz** [comment]
Thanks for the suggestion @jimmywim!
