### ISSUE TITLE
Extend mocks with support for matching nth request

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoft/m365-developer-proxy#330]
While working on building mocks for provisioning Microsoft Graph connectors, I realized that I'd need to be able to mock n-th call to the specific endpoint with a different endpoint. The idea is to simulate a long running operation of provisioning a connector schema that takes a while and finally ends successfully or fails. Today, this requires fiddling with URLs to simulate the different end states but it would be more convenient to specify on a mock response that it should match n-th request to the specified URL.

What I'd like to propose:
- extend the `response` object with `nth` property which accepts a number
- extend the mock plugin to keep track of the number of times it matched the mock with a request
- if `nth` is specified on the response, the mock plugin will apply the mock if the number of times the mock has been matched, matches the number specified on `nth`
- if `nth` isn't specified, the mock will be applied using the existing logic without considering the number of matched requests
- if `nth` is set to `0` that mock will never be applied. That will give users an easy way to temporarily disable mocks without having to remove them altogether (imagine you've got a mock for an error and success state and want to test either one, then you'd set the other one to `nth=0`)
- mocks with `nth` specified will need to be placed higher in the mocks file so that they're picked up before mocks without `nth` (which are considered more generic)

**Comment by waldekmastykarz** [comment]
Thoughts @microsoft/m365-developer-proxy-write?

**Comment by gavinbarron** [comment]
This is a cool idea and makes sense for us to provide this kind of setup.

When `nth` is match is the counter reset to 0 so that the mock will be supplied again in n requests, or is it a one and done setup?

**Comment by sebastienlevert** [comment]
I understand and think this is a cool idea also. But this is very "niche". I'm wondering if this is a scenario often seen by developers...

**Comment by waldekmastykarz** [comment]
> This is a cool idea and makes sense for us to provide this kind of setup.
> 
> When `nth` is match is the counter reset to 0 so that the mock will be supplied again in n requests, or is it a one and done setup?

nth is set to 0 on start and not reset after match, that way developers can define subsequent states

> I understand and think this is a cool idea also. But this is very "niche". I'm wondering if this is a scenario often seen by developers...

In the world of testing, this is a very common scenario that probably every testing/mocking framework supports. It's the only way to test that your code properly handles backing off on throttling and rate limiting in a non-chaos way.

**Comment by garrytrinder** [comment]
I like this idea, great suggestion @waldekmastykarz 👏

If I'm understanding correctly its like the equivalent of `getCall(n)` method in `sinonjs`? If so, I wonder if using `call` instead of `nth` for the property name would be more intuitive.

**Comment by waldekmastykarz** [comment]
Correct. Personally, I find `call` unintuitive. It doesn't communicate its intent. Imagine the following mock request setup:

```json
{
  "url": "https://graph.microsoft.com/v1.0/me?*",
  "method": "GET",
  "call": "?"
  "responseStatus": 200,
  "responseBody": {
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users/$entity",
    "businessPhones": [
      "+1 412 555 0109"
    ],
    "displayName": "Megan Bowen",
    "givenName": "Megan",
    "jobTitle": "Auditor",
    "mail": "MeganB@M365x214355.onmicrosoft.com",
    "mobilePhone": null,
    "officeLocation": "12/1110",
    "preferredLanguage": "en-US",
    "surname": "Bowen",
    "userPrincipalName": "MeganB@M365x214355.onmicrosoft.com",
    "id": "48d31887-5fad-4d73-a9f5-3c356e68a038"
  }
}
```

Seeing the word `call` doesn't express what's the expected value. It's unclear if it's meant as a noun or a verb. Without looking at documentation, you would have no idea what to put in there. Because of this ambiguity, I stand by `nth` 🙂

**Comment by garrytrinder** [comment]
Thanks for the example and confirming my understanding. Happy to stay with `nth`. 😄

**Comment by waldekmastykarz** [comment]
Thanks for the critical view and looking at alternatives 😊
