### ISSUE TITLE
Extend rate limiting plugin with configurable behavior after exceed the limit

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoft/m365-developer-proxy#334]
When you exceed the limit communicated by the rate limit plugin, you'd expect to be throttled with a 429 response. It turns out that some APIs behave differently. GitHub for example returns a 403 with a custom message.

To support other APIs beyond M365, we should extend the rate limiting plugin with configurable behavior for what to do when the limit is exceeded.

I propose:
- add new configuration property named `behaviorWhenLimitExceeded` which can be set to `Throttle` (default), or `Custom`
- add new configuration property named `limitExceededResponse` which can be set to an object with responseStatus, responseHeaders and responseBody (basically same as a mock response). This property is required when behaviorWhenLimitExceeded is set to Custom

**Comment by waldekmastykarz** [comment]
@microsoft/m365-developer-proxy-write thoughts?

**Comment by waldekmastykarz** [comment]
Yes, I've done that in the PR. I realized that we can't embed the response directly in the config because of its nested structure.

**Comment by sebastienlevert** [comment]
Absolutely agree! Extending is important and will unlock new scenarios!
