### ISSUE TITLE
[BUG]: option example is not accurate for –watch-process-names

### ISSUE THREAD

**Issue by xzf0587** [microsoft/m365-developer-proxy#351]
### Description

<img width="529" alt="image" src="https://github.com/microsoft/m365-developer-proxy/assets/16380704/90eea14a-96d1-483a-9397-e18adbd24449">

I tried to use –watch-process-names to specify monitor processes by `–watch-process-names node,msedge` as the guide shows

### Expected behaviour

It should monitor the traffic from the specific processes

### Actual behaviour

It will not work to monitor the traffic from the specific processes

### Steps to reproduce

`m365proxy.exe  -f 0 --mocks-file .\responses.sample.json --watch-process-names node,msedge`

### Microsoft 365 Developer Proxy Version

0.10.0

### Operating system (environment)

Windows

### Shell

PowerShell

### Additional Info

It works for `m365proxy.exe  -f 0 --mocks-file .\responses.sample.json --watch-process-names node msedge`
Use space instead of `,` to join the process names.

**Comment by waldekmastykarz** [comment]
Great catch. Sorry for sending you down the wrong path. We'll update it asap

**Comment by waldekmastykarz** [comment]
Updated the docs. Thanks again!
