### ISSUE TITLE
Extend documentation with .NET 4.8 setup instructions

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoft/m365-developer-proxy#352]
OK, I think I've got it. Seems like Microsoft Graph .NET SDK on .NET 4.8 uses an older HTTP adapter, which is configured to use WinHTTP API proxy settings rather than the internet proxy settings which the m365proxy enables on startup.

To use m365proxy with .NET 4.8, you need to configure it as proxy with the WinHTTP API. You can do that using the `netsh` command (run as admin):

```cmd
netsh winhttp set proxy proxy-server="http=localhost:8000;https=localhost:8000"
```

When you're done, you can reset the WinHTTP settings by calling:

```cmd
netsh winhttp reset proxy
```

Hope this helps.

@garrytrinder we should add this to our docs

/cc: @gavinbarron @sebastienlevert

_Originally posted by @waldekmastykarz in https://github.com/microsoft/m365-developer-proxy/issues/346#issuecomment-1724988859_

**Comment by garrytrinder** [comment]
I suggest we add a page for this under our [Common problems](https://github.com/microsoft/m365-developer-proxy/wiki/How-to-guides#common-problems) section in the How to guides page. Something like, `Why is proxy not detecting requests from my .NET 4.8 app`

**Comment by garrytrinder** [comment]
A new [guide](https://github.com/microsoft/m365-developer-proxy/wiki/Why-is-proxy-not-intercepting-requests-from-my-.net-4.8-app) has been added to the wiki and I added a remark with link to the guide on the Windows 11 instructions which is under the [Start the proxy](https://github.com/microsoft/m365-developer-proxy/wiki/Using-the-proxy-for-the-first-time#1-start-the-proxy) section in the [Using the proxy for the first time](https://github.com/microsoft/m365-developer-proxy/wiki/Using-the-proxy-for-the-first-time) page.
