### ISSUE TITLE
[Release]: Developer proxy in Winget

### ISSUE THREAD

**Issue by svrooij** [microsoft/m365-developer-proxy#354]
### Description

```Shell
 > winget search "Microsoft 365 developer Proxy"
No package found matching input criteria.
```

![image](https://github.com/microsoft/m365-developer-proxy/assets/1292510/bc24a9b9-a7c8-4061-88e8-98767b3d2489)

![image](https://github.com/microsoft/m365-developer-proxy/assets/1292510/5102bc7b-e685-4f06-8dd5-4d5e0ef84959)

### Expected behaviour

I expected to install the developer proxy through winget.
And I expected it to be signed, so it's not blocked by Microsoft Defender

### Actual behaviour

Instead it showed `No package found matching input criteria.`

### Steps to reproduce

`winget search "Microsoft 365 developer Proxy"`

### Microsoft 365 Developer Proxy Version

0.0.0

### Operating system (environment)

Windows

### Shell

PowerShell

### Additional Info

I know this is not really a bug, I hope you forgive me?

**Comment by waldekmastykarz** [comment]
Het @svrooij, at the moment we don't have the proxy available on winget yet. Let's continue the conversation on #11 which is the original issue on the topic
