### ISSUE TITLE
Installation & Setup

### ISSUE THREAD

**Issue by ferrarirosso** [microsoft/m365-developer-proxy#361]
### Description

Referring to the [installation instructions](https://github.com/microsoft/m365-developer-proxy/wiki/Installation), I had to make m365proxy executable with chmod +x on the file

### Expected behaviour

File is executable after unzipping it
or
the documentation is updated

### Actual behaviour

Executable is opened showing executable code in a "windows"

### Steps to reproduce

Download osx64, unzip it

### Microsoft 365 Developer Proxy Version

0.12.1

### Operating system (environment)

macOS

### Shell

zsh

**Comment by garrytrinder** [comment]
Thank you for letting us know @ferrarirosso 👍 

Apologies for the inconvenience. We will get the instructions updated.

**Comment by garrytrinder** [comment]
Added a new step to the macOS instructions to make the file an executable.

Thanks again for reporting @ferrarirosso 👍

**Comment by ferrarirosso** [comment]
@garrytrinder thx !
