### ISSUE TITLE
Record minimal permissions information in a file

### ISSUE THREAD

**Issue by xzf0587** [microsoft/m365-developer-proxy#366]
### Description

![image](https://github.com/microsoft/m365-developer-proxy/assets/16380704/d73e8a71-29d3-4d4c-a22d-64527793656e)
We can get the message about minimal permissions after stopping recording in terminal.
But the message will not be logged in the summary file.

### Expected behaviour

The message about minimal permissions should be logged in summary file.
It would be better to provide an option to store this message in specific file in some format(maybe Json) which is easy to resolve by process automatically. 

### Actual behaviour

No message about minimal permissions

### Steps to reproduce

1. launch the proxy by
`./m365proxy.exe --mocks-file .\responses.sample.json --watch-process-names node msedge --record --summary-file-path report.md`

2. access to some graph api via Edge.
3. stop the proxy.

### Microsoft 365 Developer Proxy Version

0.10.0

### Operating system (environment)

Windows

### Shell

PowerShell

**Comment by waldekmastykarz** [comment]
Thank you for the suggestion @xzf0587. The summary file is meant for use with the summary plugin only, sorry for the confusion. That said, I totally understand the need to store the information in a file for further processing. Great suggestion 👍

**Comment by waldekmastykarz** [comment]
Would a structure like this work for you @xzf0587?

```json
{
  "operations": [
    {
      "method": "GET",
      "endpoint": "/me"
    },
    {
      "method": "GET",
      "endpoint": "/users"
    }
  ],
  "permissionsFromTheToken": [
    "User.Read",
    "Mail.Send"
  ],
  "minimalPermissions": [
    "User.Read"
  ]
}
```

@gavinbarron, @sebastienlevert, @garrytrinder any feedback?

**Comment by xzf0587** [comment]
> Would a structure like this work for you @xzf0587?
> 
> ```json
> {
>   "operations": [
>     {
>       "method": "GET",
>       "endpoint": "/me"
>     },
>     {
>       "method": "GET",
>       "endpoint": "/users"
>     }
>   ],
>   "permissionsFromTheToken": [
>     "User.Read",
>     "Mail.Send"
>   ],
>   "minimalPermissions": [
>     "User.Read"
>   ]
> }
> ```
> 
> @gavinbarron, @sebastienlevert, @garrytrinder any feedback?

Sure. It is good.
I think there could be a small update for key order that move the key `permissionsFromTheToken` and `minimalPermissions` above key `operations`.
Because the operations information sometimes could be too long to find the `minimalPermissions` at first glance.

**Comment by waldekmastykarz** [comment]
Here's the updated version:

```json
{
  "minimalPermissions": [
    "User.Read"
  ],
  "permissionsFromTheToken": [
    "User.Read",
    "Mail.Send"
  ],
  "operations": [
    {
      "method": "GET",
      "endpoint": "/me"
    },
    {
      "method": "GET",
      "endpoint": "/users"
    }
  ]
}
```

**Comment by sebastienlevert** [comment]
That works for me!
