### ISSUE TITLE
Add support for slow responses

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoft/m365-developer-proxy#37]
Extend the proxy with ability to test slow API responses.

### Rationale

One aspect of testing how applications use an API is how they respond to slow API responses. Is it obvious that content is loading? Is the whole application unresponsive? Is the application failing because it expects a response in a certain timeframe? Graph Developer Proxy can help developers validate the user experience when the API responds slowly.

### Spec

- [ ] introduce app setting named `minDelayMs`, that defines the lower range of the delay in milliseconds added to API response. Default value `500`
- [ ] introduce app setting named `maxDelayMs`, that defines the upper range of the delay in milliseconds added to API response. Default value `10000`
- [ ] introduce option named `--min-delay` that allows users to override the value of `minDelayMs` as configured in appSettings. When not specified, uses the value from appSettings.
- [ ] introduce option named `--max-delay` that allows users to override the value of `maxDelayMs` as configured in appSettings. When not specified, uses the value from appSettings.
- [ ] introduce option named `--slow-responses` which is a flag. When used, it will cause the proxy to add a random delay from range `minDelayMs <= x <= maxDelayMs` to each API response (mocked or not)

**Comment by waldekmastykarz** [comment]
The main scenario for this feature is to help developers understand how their app will look like, when the response from the API isn't instantaneous: will the app be blocked and show an empty page until all requests complete, will there be content shifts that have a negative impact on the UX, etc.

**Comment by gavinbarron** [comment]
Could we also add an optional minimum delay to the parameter e.g. `--slow-responses` and `--slow-responses 2000` are valid but the second ensures a minimum of 2000ms delay is added to responses?

**Comment by waldekmastykarz** [comment]
> Could we also add an optional minimum delay to the parameter e.g. `--slow-responses` and `--slow-responses 2000` are valid but the second ensures a minimum of 2000ms delay is added to responses?

It's a good idea to offer the ability to specify a minimum value @gavinbarron. How could make it less ambiguous if the specified value is the exact delay, the minimum or the maximum?

**Comment by gavinbarron** [comment]
`--min-delay` and `--max-delay` seem like good candidates with `--slow-responses` using the min and max delay defaults that is in the appsettings.json file?
providing either `--min-delay` or `--max-delay` will enable slow response mode and use the default for the unspecified value

**Comment by waldekmastykarz** [comment]
Are the min and max values something you'd be likely to change on each proxy run and hence something we should expose as options, or it's rather something you'd configure once in appSettings and then use as your preferred values? Trying to think if we have to add two more options or if a config setting be sufficient.

**Comment by gavinbarron** [comment]
In my mind they're likely something that I'd put in config as defaults and then be able to override as a command line option.

**Comment by waldekmastykarz** [comment]
Updated spec. Have I captured everything correctly @gavinbarron?

**Comment by sebastienlevert** [comment]
Is there a reason where we specify the minDelay*Ms*? I don't think it's required and should be documented (Maybe using JsonC in the config file, and in our docs). I don't feel it adds value.

**Comment by gavinbarron** [comment]
> Updated spec. Have I captured everything correctly @gavinbarron?

That captures everything correctly from my point of view. 

> Is there a reason where we specify the minDelayMs?

I assume you're meaning the Ms suffix on these settings? IMO when reading the code inside the proxy that uses this setting it would also have the Ms suffix and make it more apparent what units the delay is in without the need to change to using jsonc and it's would also be visible in the C# code in this form.
I'm all for eliminating things that don't have value, but keeping the affordance of settings high through convention based naming is a nice thing to me, I hate to have to go look for documentation to for the units of time being used in these scenarios.

**Comment by waldekmastykarz** [comment]
@gavinbarron is right @sebastienlevert. The idea is, that when you're looking at settings you immediately know which unit we expect the value to be in, without having to second guess it/look up in docs/rely on editor features such as intellisense that you might not have. Basically it's aiming to make it self-explanatory.

**Comment by garrytrinder** [comment]
Just want to add that we should think about the supporting documentation for this in the spec so we don't forget about how to articulate this new feature to our audience. At minimum I think we should provide a How-to guide and update the technical reference.

**Comment by waldekmastykarz** [comment]
Completed in #321
