### ISSUE TITLE
[BUG]: "The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception." error

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoft/m365-developer-proxy#370]
### Description

After starting the proxy you see the following error:

The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.

### Expected behaviour

No error

### Actual behaviour

Error

### Steps to reproduce

Start the proxy

### Microsoft 365 Developer Proxy Version

v0.13.0-beta.1

### Operating system (environment)

macOS

### Shell

zsh

### Additional Info

Test using the published release

**Comment by waldekmastykarz** [comment]
This happens when the `libe_sqlite3.dylib` file is not approved to be executed (similarly to the main proxy executable). @garrytrinder let's include it in our KB in case someone else runs against it

**Comment by garrytrinder** [comment]
I've added and instruction to make libe_sqlite3.dylib an executable in the macOS instructions on https://github.com/microsoft/m365-developer-proxy/wiki/Using-the-proxy-for-the-first-time and I've added a page, https://github.com/microsoft/m365-developer-proxy/wiki/The-type-initializer-for-'Microsoft.Data.Sqlite.SqliteConnection'-threw-an-exception, under the Common Problems section of the How-to guides page.
