### ISSUE TITLE
[BUG]: Unexpected error when the proxy process is terminated

### ISSUE THREAD

**Issue by xzf0587** [microsoft/m365-developer-proxy#371]
### Description

There is an error when I terminated the proxy process.
The error message is 
>Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'OPTIONS ?https://graph.microsoft.com/v1.0/me' was not present in the dictionary.

### Expected behaviour

It could exit successfully

### Actual behaviour

Here is the log in output.
<img width="954" alt="image" src="https://github.com/microsoft/m365-developer-proxy/assets/16380704/fda1e234-2130-4508-9f07-42661659e0f1">

PS C:\Users\zhaofengxu\TeamsApps\hello-world-tab-with-backend_3> npm run m365proxy:error

\> teamsfx-template-tab@0.1.0 m365proxy:error
\> cd m365proxy && m365proxy -f 100 --watch-process-names node msedge --record

Mock responses for 0 url patterns loaded from C:\Users\zhaofengxu\TeamsApps\hello-world-tab-with-backend_3\m365proxy\responses.json
Listening on 0.0.0.0:8000...
Set endpoint at Ip 0.0.0.0 and port: 8000 as System HTTP Proxy
Set endpoint at Ip 0.0.0.0 and port: 8000 as System HTTPS Proxy
Press CTRL+C to stop the Microsoft 365 Developer Proxy

◉ Recording...
 request     GET https://graph.microsoft.com/v1.0/me
   chaos   ╭ 502 BadGateway
           ╰ GET https://graph.microsoft.com/v1.0/me
 warning   ╭ To improve performance of your application, use the $select parameter.
           │ More info at https://aka.ms/m365/proxy/guidance/select
           ╰ GET https://graph.microsoft.com/v1.0/me
 request     GET https://graph.microsoft.com/v1.0/me
 warning   ╭ Another request to /v1.0/me intercepted within 5 seconds.
           │ Last intercepted at 10/30/2023 5:44:55 PM.
           │ Consider using cache to avoid calling the API too often.
           ╰ GET https://graph.microsoft.com/v1.0/me
   chaos   ╭ 502 BadGateway
           ╰ GET https://graph.microsoft.com/v1.0/me
 warning   ╭ To improve performance of your application, use the $select parameter.
           │ More info at https://aka.ms/m365/proxy/guidance/select
           ╰ GET https://graph.microsoft.com/v1.0/me
 request     GET https://graph.microsoft.com/v1.0/me/calendarview
   chaos   ╭ 500 InternalServerError
           ╰ GET https://graph.microsoft.com/v1.0/me/calendarview
 request     GET https://graph.microsoft.com/v1.0/users/me/photo/$value
   chaos   ╭ 500 InternalServerError
           ╰ GET https://graph.microsoft.com/v1.0/users/me/photo/$value
○ Stopped recording
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'OPTIONS https://graph.microsoft.com/v1.0/me' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft365.DeveloperProxy.Plugins.RequestLogs.ExecutionSummaryPlugin.GetGroupedByUrlData(IEnumerable`1 requestLogs)
   at Microsoft365.DeveloperProxy.Plugins.RequestLogs.ExecutionSummaryPlugin.GetGroupedByUrlReport(IEnumerable`1 requestLogs)
   at Microsoft365.DeveloperProxy.Plugins.RequestLogs.ExecutionSummaryPlugin.AfterRecordingStop(Object sender, RecordingArgs e)
   at Microsoft365.DeveloperProxy.Abstractions.PluginEvents.RaiseRecordingStopped(RecordingArgs args)
   at Microsoft365.DeveloperProxy.ProxyEngine.StopRecording()
   at Microsoft365.DeveloperProxy.ProxyEngine.Console_CancelKeyPress(Object sender, ConsoleCancelEventArgs e)
   at System.Console.HandlePosixSignal(PosixSignalContext ctx)
   at System.Runtime.InteropServices.PosixSignalRegistration.HandlerRoutine(Int32 dwCtrlType)
Terminate batch job (Y/N)?

### Steps to reproduce

1. launch the proxy.
2. send request as the logs show.
3. terminate the process.

The error is not stable reproducted. And it can occur when response mock is configured or error mock is configured.

### Microsoft 365 Developer Proxy Version

0.12.1

### Operating system (environment)

Windows

### Shell

PowerShell

**Comment by garrytrinder** [comment]
Thanks for the bug report @xzf0587, apologies for the trouble.

This is a known issue and we have a PR to resolve this https://github.com/microsoft/m365-developer-proxy/pull/369

For now, you should stop recording before you close the proxy process by using `S`, see [Keyboard shortcuts](https://github.com/microsoft/m365-developer-proxy/wiki/Keyboard-shortcuts).

**Comment by xzf0587** [comment]
Close it for duplicate issue.

**Comment by waldekmastykarz** [comment]
Are you sure this is the same issue @garrytrinder? #369 fixes the problem of proxy not waiting for plugins before closing. This issue is about an exception being thrown. I think they're different and suggest we research them

**Comment by waldekmastykarz** [comment]
It's interesting, that following the log proxy has not intercepted an OPTIONS request, yet somehow it ended up in the internals. I'll try to repro it

**Comment by waldekmastykarz** [comment]
@xzf0587 could you please share with us your `m365proxyrc.json` file so that we can use proxy using the same configuration as you are?

**Comment by garrytrinder** [comment]
> Are you sure this is the same issue @garrytrinder? #369 fixes the problem of proxy not waiting for plugins before closing. This issue is about an exception being thrown. I think they're different and suggest we research them

Ah yes, good spot @waldekmastykark, apologies @xzf0587.

**Comment by waldekmastykarz** [comment]
OK, I can confirm that I can repro the issue. I'll get on with fixing it
